version: '3'

services:
    app:
        build: .docker/node
        entrypoint: .docker/node/entrypoint.sh
        container_name: apivendas-app
        ports:
            - '3333:3333'
        volumes:
            - .:/home/node/app
        depends_on:
            - db
            - redis
    db:
        build: .docker/postgres
        container_name: apivendas-db
        restart: always
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=apivendas
        volumes:
            - pg_data:/var/lib/postgresql/data

    redis:
        image: 'bitnami/redis:latest'
        container_name: apivendas-redis
        ports:
            - '6379:6379'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
volumes:
    pg_data:
